// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xescugc/rebost/deletion (interfaces: Repository)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	deletion "github.com/xescugc/rebost/deletion"
)

// DeletionRepository is a mock of Repository interface.
type DeletionRepository struct {
	ctrl     *gomock.Controller
	recorder *DeletionRepositoryMockRecorder
}

// DeletionRepositoryMockRecorder is the mock recorder for DeletionRepository.
type DeletionRepositoryMockRecorder struct {
	mock *DeletionRepository
}

// NewDeletionRepository creates a new mock instance.
func NewDeletionRepository(ctrl *gomock.Controller) *DeletionRepository {
	mock := &DeletionRepository{ctrl: ctrl}
	mock.recorder = &DeletionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *DeletionRepository) EXPECT() *DeletionRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *DeletionRepository) Count(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *DeletionRepositoryMockRecorder) Count(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*DeletionRepository)(nil).Count), arg0)
}

// Create mocks base method.
func (m *DeletionRepository) Create(arg0 context.Context, arg1 *deletion.Deletion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *DeletionRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*DeletionRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *DeletionRepository) Delete(arg0 context.Context, arg1 *deletion.Deletion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *DeletionRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*DeletionRepository)(nil).Delete), arg0, arg1)
}

// First mocks base method.
func (m *DeletionRepository) First(arg0 context.Context) (*deletion.Deletion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "First", arg0)
	ret0, _ := ret[0].(*deletion.Deletion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// First indicates an expected call of First.
func (mr *DeletionRepositoryMockRecorder) First(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "First", reflect.TypeOf((*DeletionRepository)(nil).First), arg0)
}
