// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xescugc/rebost/idxttl (interfaces: Repository)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	idxttl "github.com/xescugc/rebost/idxttl"
)

// IDXTTLRepository is a mock of Repository interface.
type IDXTTLRepository struct {
	ctrl     *gomock.Controller
	recorder *IDXTTLRepositoryMockRecorder
}

// IDXTTLRepositoryMockRecorder is the mock recorder for IDXTTLRepository.
type IDXTTLRepositoryMockRecorder struct {
	mock *IDXTTLRepository
}

// NewIDXTTLRepository creates a new mock instance.
func NewIDXTTLRepository(ctrl *gomock.Controller) *IDXTTLRepository {
	mock := &IDXTTLRepository{ctrl: ctrl}
	mock.recorder = &IDXTTLRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *IDXTTLRepository) EXPECT() *IDXTTLRepositoryMockRecorder {
	return m.recorder
}

// CreateOrReplace mocks base method.
func (m *IDXTTLRepository) CreateOrReplace(arg0 context.Context, arg1 *idxttl.IDXTTL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrReplace", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrReplace indicates an expected call of CreateOrReplace.
func (mr *IDXTTLRepositoryMockRecorder) CreateOrReplace(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrReplace", reflect.TypeOf((*IDXTTLRepository)(nil).CreateOrReplace), arg0, arg1)
}

// Delete mocks base method.
func (m *IDXTTLRepository) Delete(arg0 context.Context, arg1 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *IDXTTLRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*IDXTTLRepository)(nil).Delete), arg0, arg1)
}

// Filter mocks base method.
func (m *IDXTTLRepository) Filter(arg0 context.Context, arg1 time.Time) ([]*idxttl.IDXTTL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", arg0, arg1)
	ret0, _ := ret[0].([]*idxttl.IDXTTL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *IDXTTLRepositoryMockRecorder) Filter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*IDXTTLRepository)(nil).Filter), arg0, arg1)
}

// Find mocks base method.
func (m *IDXTTLRepository) Find(arg0 context.Context, arg1 time.Time) (*idxttl.IDXTTL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(*idxttl.IDXTTL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *IDXTTLRepositoryMockRecorder) Find(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*IDXTTLRepository)(nil).Find), arg0, arg1)
}
