// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xescugc/rebost/scrub (interfaces: Repository)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	scrub "github.com/xescugc/rebost/scrub"
)

// ScrubRepository is a mock of Repository interface.
type ScrubRepository struct {
	ctrl     *gomock.Controller
	recorder *ScrubRepositoryMockRecorder
}

// ScrubRepositoryMockRecorder is the mock recorder for ScrubRepository.
type ScrubRepositoryMockRecorder struct {
	mock *ScrubRepository
}

// NewScrubRepository creates a new mock instance.
func NewScrubRepository(ctrl *gomock.Controller) *ScrubRepository {
	mock := &ScrubRepository{ctrl: ctrl}
	mock.recorder = &ScrubRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ScrubRepository) EXPECT() *ScrubRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *ScrubRepository) Create(arg0 context.Context, arg1 scrub.Scrub) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *ScrubRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*ScrubRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *ScrubRepository) Delete(arg0 context.Context, arg1 *scrub.Scrub) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *ScrubRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*ScrubRepository)(nil).Delete), arg0, arg1)
}

// First mocks base method.
func (m *ScrubRepository) First(arg0 context.Context) (*scrub.Scrub, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "First", arg0)
	ret0, _ := ret[0].(*scrub.Scrub)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// First indicates an expected call of First.
func (mr *ScrubRepositoryMockRecorder) First(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "First", reflect.TypeOf((*ScrubRepository)(nil).First), arg0)
}
