// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xescugc/rebost/volume (interfaces: Local)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	deletion "github.com/xescugc/rebost/deletion"
	replica "github.com/xescugc/rebost/replica"
	scrub "github.com/xescugc/rebost/scrub"
	state "github.com/xescugc/rebost/state"
	volume "github.com/xescugc/rebost/volume"
)

// VolumeLocal is a mock of Local interface.
type VolumeLocal struct {
	ctrl     *gomock.Controller
	recorder *VolumeLocalMockRecorder
}

// VolumeLocalMockRecorder is the mock recorder for VolumeLocal.
type VolumeLocalMockRecorder struct {
	mock *VolumeLocal
}

// NewVolumeLocal creates a new mock instance.
func NewVolumeLocal(ctrl *gomock.Controller) *VolumeLocal {
	mock := &VolumeLocal{ctrl: ctrl}
	mock.recorder = &VolumeLocalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *VolumeLocal) EXPECT() *VolumeLocalMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *VolumeLocal) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *VolumeLocalMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*VolumeLocal)(nil).Close))
}

// CreateFile mocks base method.
func (m *VolumeLocal) CreateFile(arg0 context.Context, arg1 string, arg2 io.ReadCloser, arg3 int, arg4 time.Duration, arg5 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFile", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFile indicates an expected call of CreateFile.
func (mr *VolumeLocalMockRecorder) CreateFile(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFile", reflect.TypeOf((*VolumeLocal)(nil).CreateFile), arg0, arg1, arg2, arg3, arg4, arg5)
}

// DeleteDeletion mocks base method.
func (m *VolumeLocal) DeleteDeletion(arg0 context.Context, arg1 *deletion.Deletion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDeletion", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDeletion indicates an expected call of DeleteDeletion.
func (mr *VolumeLocalMockRecorder) DeleteDeletion(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDeletion", reflect.TypeOf((*VolumeLocal)(nil).DeleteDeletion), arg0, arg1)
}

// DeleteFile mocks base method.
func (m *VolumeLocal) DeleteFile(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *VolumeLocalMockRecorder) DeleteFile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*VolumeLocal)(nil).DeleteFile), arg0, arg1)
}

// DeleteReplica mocks base method.
func (m *VolumeLocal) DeleteReplica(arg0 context.Context, arg1 *replica.Replica) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReplica", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReplica indicates an expected call of DeleteReplica.
func (mr *VolumeLocalMockRecorder) DeleteReplica(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReplica", reflect.TypeOf((*VolumeLocal)(nil).DeleteReplica), arg0, arg1)
}

// DeleteScrub mocks base method.
func (m *VolumeLocal) DeleteScrub(arg0 context.Context, arg1 *scrub.Scrub) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScrub", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScrub indicates an expected call of DeleteScrub.
func (mr *VolumeLocalMockRecorder) DeleteScrub(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScrub", reflect.TypeOf((*VolumeLocal)(nil).DeleteScrub), arg0, arg1)
}

// GetFile mocks base method.
func (m *VolumeLocal) GetFile(arg0 context.Context, arg1 string) (io.ReadCloser, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", arg0, arg1)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFile indicates an expected call of GetFile.
func (mr *VolumeLocalMockRecorder) GetFile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*VolumeLocal)(nil).GetFile), arg0, arg1)
}

// GetState mocks base method.
func (m *VolumeLocal) GetState(arg0 context.Context) (*state.State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetState", arg0)
	ret0, _ := ret[0].(*state.State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetState indicates an expected call of GetState.
func (mr *VolumeLocalMockRecorder) GetState(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetState", reflect.TypeOf((*VolumeLocal)(nil).GetState), arg0)
}

// HasFile mocks base method.
func (m *VolumeLocal) HasFile(arg0 context.Context, arg1 string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasFile", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// HasFile indicates an expected call of HasFile.
func (mr *VolumeLocalMockRecorder) HasFile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasFile", reflect.TypeOf((*VolumeLocal)(nil).HasFile), arg0, arg1)
}

// HasPendingReplicas mocks base method.
func (m *VolumeLocal) HasPendingReplicas(arg0 context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPendingReplicas", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPendingReplicas indicates an expected call of HasPendingReplicas.
func (mr *VolumeLocalMockRecorder) HasPendingReplicas(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPendingReplicas", reflect.TypeOf((*VolumeLocal)(nil).HasPendingReplicas), arg0)
}

// ID mocks base method.
func (m *VolumeLocal) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *VolumeLocalMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*VolumeLocal)(nil).ID))
}

// NextDeletion mocks base method.
func (m *VolumeLocal) NextDeletion(arg0 context.Context) (*deletion.Deletion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextDeletion", arg0)
	ret0, _ := ret[0].(*deletion.Deletion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextDeletion indicates an expected call of NextDeletion.
func (mr *VolumeLocalMockRecorder) NextDeletion(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextDeletion", reflect.TypeOf((*VolumeLocal)(nil).NextDeletion), arg0)
}

// NextReplica mocks base method.
func (m *VolumeLocal) NextReplica(arg0 context.Context) (*replica.Replica, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextReplica", arg0)
	ret0, _ := ret[0].(*replica.Replica)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextReplica indicates an expected call of NextReplica.
func (mr *VolumeLocalMockRecorder) NextReplica(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextReplica", reflect.TypeOf((*VolumeLocal)(nil).NextReplica), arg0)
}

// NextScrub mocks base method.
func (m *VolumeLocal) NextScrub(arg0 context.Context) (*scrub.Scrub, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextScrub", arg0)
	ret0, _ := ret[0].(*scrub.Scrub)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextScrub indicates an expected call of NextScrub.
func (mr *VolumeLocalMockRecorder) NextScrub(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextScrub", reflect.TypeOf((*VolumeLocal)(nil).NextScrub), arg0)
}

// OverwriteFileContent mocks base method.
func (m *VolumeLocal) OverwriteFileContent(arg0 context.Context, arg1 string, arg2 io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OverwriteFileContent", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// OverwriteFileContent indicates an expected call of OverwriteFileContent.
func (mr *VolumeLocalMockRecorder) OverwriteFileContent(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OverwriteFileContent", reflect.TypeOf((*VolumeLocal)(nil).OverwriteFileContent), arg0, arg1, arg2)
}

// PrepareForDrain mocks base method.
func (m *VolumeLocal) PrepareForDrain(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareForDrain", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// PrepareForDrain indicates an expected call of PrepareForDrain.
func (mr *VolumeLocalMockRecorder) PrepareForDrain(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareForDrain", reflect.TypeOf((*VolumeLocal)(nil).PrepareForDrain), arg0)
}

// PurgeAllFiles mocks base method.
func (m *VolumeLocal) PurgeAllFiles(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PurgeAllFiles", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// PurgeAllFiles indicates an expected call of PurgeAllFiles.
func (mr *VolumeLocalMockRecorder) PurgeAllFiles(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeAllFiles", reflect.TypeOf((*VolumeLocal)(nil).PurgeAllFiles), arg0)
}

// Reset mocks base method.
func (m *VolumeLocal) Reset(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *VolumeLocalMockRecorder) Reset(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*VolumeLocal)(nil).Reset), arg0)
}

// StatFile mocks base method.
func (m *VolumeLocal) StatFile(arg0 context.Context, arg1 string) (*volume.FileStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatFile", arg0, arg1)
	ret0, _ := ret[0].(*volume.FileStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StatFile indicates an expected call of StatFile.
func (mr *VolumeLocalMockRecorder) StatFile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatFile", reflect.TypeOf((*VolumeLocal)(nil).StatFile), arg0, arg1)
}

// SynchronizeReplicas mocks base method.
func (m *VolumeLocal) SynchronizeReplicas(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SynchronizeReplicas", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SynchronizeReplicas indicates an expected call of SynchronizeReplicas.
func (mr *VolumeLocalMockRecorder) SynchronizeReplicas(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SynchronizeReplicas", reflect.TypeOf((*VolumeLocal)(nil).SynchronizeReplicas), arg0, arg1)
}

// UpdateFileReplica mocks base method.
func (m *VolumeLocal) UpdateFileReplica(arg0 context.Context, arg1 string, arg2 []string, arg3 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFileReplica", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFileReplica indicates an expected call of UpdateFileReplica.
func (mr *VolumeLocalMockRecorder) UpdateFileReplica(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFileReplica", reflect.TypeOf((*VolumeLocal)(nil).UpdateFileReplica), arg0, arg1, arg2, arg3)
}

// UpdateReplica mocks base method.
func (m *VolumeLocal) UpdateReplica(arg0 context.Context, arg1 *replica.Replica, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReplica", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReplica indicates an expected call of UpdateReplica.
func (mr *VolumeLocalMockRecorder) UpdateReplica(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReplica", reflect.TypeOf((*VolumeLocal)(nil).UpdateReplica), arg0, arg1, arg2)
}
